### ISSUE TITLE
Transition abort typo

### ISSUE THREAD

**Issue by chookie** [coryhouse/react-flux-starter-kit#10]
I think there is a typo at about 1:50 of the "Transitions" module where you have typed ```transition.about()``` instead of ```transition.abort()```.

This is a really excellent course Cory, very practical and real world thank you.  Looking forward to your ES6 course once I finish this one.

**Comment by coryhouse** [comment]
Hi @chookie - Yes, that's a typo. You're correct. I've just uploaded a patch for this. Thanks!

**Comment by coryhouse** [comment]
The course has been updated as of 6/2019 so this is no longer relevant.
