### ISSUE TITLE
setState is async

### ISSUE THREAD

**Issue by chookie** [coryhouse/react-flux-starter-kit#11]
Sorry to be back again but I think the call to toastr.success and transitionTo should be in a callback since setState is asynchronous.  I could not work out why I kept getting the warning about leaving changes until I remembered from another course.

I think in the module _React Forms/Transitions:3:35_ I think the code should be something like:
```javascript
  this.setState({dirty: false}, function() {
    toastr.success('Author saved.');
    this.transitionTo('authors');
  });
```

Again, great course thanks.

**Comment by coryhouse** [comment]
That's a great point. I've added this to the list of items I plan to patch.

**Comment by coryhouse** [comment]
The course has been updated as of 6/2019. This issue has been addressed in the update.
