### ISSUE TITLE
npm start -s not working with forever

### ISSUE THREAD

**Issue by ramprasadgs** [coryhouse/react-flux-starter-kit#16]
Hi Cory!

Thanks for amazing course on react redux.
I was trying to run npm install with forever package but it's failing with following errors:

node version v6.10.3
npm version 3.10.10
Command used : 
1. forever start -c "npm start" ./ in the folder where package.json exist.
2.forever start -c "npm start" ./tools/srcServer.js 

When i run command 1 : 
data:    :21102 - > nerm@1.0.0 prestart /home/ubuntu/code/codeschool/NERM
data:    :21102 - > babel-node tools/startMessage.js
data:    :21102 - Starting app in dev mode...
data:    :21102 - > nerm@1.0.0 start /home/ubuntu/code/codeschool/NERM
data:    :21102 - > npm-run-all --parallel test:watch open:src lint:watch "/home/ubuntu/code/codeschool/NERM/"
data:    :21102 - ERROR: Task not found: "/home/ubuntu/code/codeschool/NERM/"
data:    :21102 - npm ERR! Linux 4.4.0-1022-aws
data:    :21102 - npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.10.3/bin/node" "/home/ubuntu/.nvm/versions/node/v6.10.3/bin/npm" "start" "/home/ubuntu/code/codeschool/NERM/"
data:    :21102 - npm ERR! node v6.10.3
data:    :21102 - npm ERR! npm  v3.10.10
data:    :21102 - npm ERR! code ELIFECYCLE
data:    :21102 - npm ERR! nerm@1.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch "/home/ubuntu/code/codeschool/NERM/"`
data:    :21102 - npm ERR! Exit status 1
data:    :21102 - npm ERR! 
data:    :21102 - npm ERR! Failed at the nerm@1.0.0 start script 'npm-run-all --parallel test:watch open:src lint:watch "/home/ubuntu/code/codeschool/NERM/"'.
data:    :21102 - npm ERR! Make sure you have the latest version of node.js and npm installed.
data:    :21102 - npm ERR! If you do, this is most likely a problem with the nerm package,
data:    :21102 - npm ERR! not with npm itself.
data:    :21102 - npm ERR! Tell the author that this fails on your system:
data:    :21102 - npm ERR!     npm-run-all --parallel test:watch open:src lint:watch "/home/ubuntu/code/codeschool/NERM/"
data:    :21102 - npm ERR! You can get information on how to open an issue for this project with:
data:    :21102 - npm ERR!     npm bugs nerm
data:    :21102 - npm ERR! Or if that isn't available, you can get their info via:
data:    :21102 - npm ERR!     npm owner ls nerm
data:    :21102 - npm ERR! There is likely additional logging output above.
data:    :21102 - npm ERR! Please include the following file with any support request:
data:    :21102 - npm ERR!     /home/ubuntu/code/codeschool/NERM/npm-debug.log
data:    :21102 - error: Forever detected script exited with code: 1
data:    :21102 - error: Script restart attempt #1
data:    :21102 - > nerm@1.0.0 prestart /home/ubuntu/code/codeschool/NERM
data:    :21102 - > babel-node tools/startMessage.js
data:    :21102 - Starting app in dev mode...
data:    :21102 - > nerm@1.0.0 start /home/ubuntu/code/codeschool/NERM
data:    :21102 - > npm-run-all --parallel test:watch open:src lint:watch "/home/ubuntu/code/codeschool/NERM/"
data:    :21102 - ERROR: Task not found: "/home/ubuntu/code/codeschool/NERM/"
data:    :21102 - npm ERR! Linux 4.4.0-1022-aws
data:    :21102 - npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.10.3/bin/node" "/home/ubuntu/.nvm/versions/node/v6.10.3/bin/npm" "start" "/home/ubuntu/code/codeschool/NERM/"
data:    :21102 - npm ERR! node v6.10.3
data:    :21102 - npm ERR! npm  v3.10.10
data:    :21102 - npm ERR! code ELIFECYCLE
data:    :21102 - npm ERR! nerm@1.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch "/home/ubuntu/code/codeschool/NERM/"`
data:    :21102 - npm ERR! Exit status 1
data:    :21102 - npm ERR! 
data:    :21102 - npm ERR! Failed at the nerm@1.0.0 start script 'npm-run-all --parallel test:watch open:src lint:watch "/home/ubuntu/code/codeschool/NERM/"'.
data:    :21102 - npm ERR! Make sure you have the latest version of node.js and npm installed.
data:    :21102 - npm ERR! If you do, this is most likely a problem with the nerm package,
data:    :21102 - npm ERR! not with npm itself.
data:    :21102 - npm ERR! Tell the author that this fails on your system:
data:    :21102 - npm ERR!     npm-run-all --parallel test:watch open:src lint:watch "/home/ubuntu/code/codeschool/NERM/"
data:    :21102 - npm ERR! You can get information on how to open an issue for this project with:
data:    :21102 - npm ERR!     npm bugs nerm
data:    :21102 - npm ERR! Or if that isn't available, you can get their info via:
data:    :21102 - npm ERR!     npm owner ls nerm
data:    :21102 - npm ERR! There is likely additional logging output above.
data:    :21102 - npm ERR! Please include the following file with any support request:
data:    :21102 - npm ERR!     /home/ubuntu/code/codeschool/NERM/npm-debug.log
data:    :21102 - error: Forever detected script exited with code: 1
data:    :21102 - error: Script restart attempt #2
data:    :21102 - > nerm@1.0.0 prestart /home/ubuntu/code/codeschool/NERM
data:    :21102 - > babel-node tools/startMessage.js

errors when i run command 2 : 

data:    tools/srcServer.js:23101 - > nerm@1.0.0 prestart /home/ubuntu/code/codeschool/NERM
data:    tools/srcServer.js:23101 - > babel-node tools/startMessage.js
data:    tools/srcServer.js:23101 - Starting app in dev mode...
data:    tools/srcServer.js:23101 - > nerm@1.0.0 start /home/ubuntu/code/codeschool/NERM
data:    tools/srcServer.js:23101 - > npm-run-all --parallel test:watch open:src lint:watch "/home/ubuntu/code/codeschool/NERM/tools/srcServer.js"
data:    tools/srcServer.js:23101 - ERROR: Task not found: "/home/ubuntu/code/codeschool/NERM/tools/srcServer.js"
data:    tools/srcServer.js:23101 - npm ERR! Linux 4.4.0-1022-aws
data:    tools/srcServer.js:23101 - npm ERR! argv "/home/ubuntu/.nvm/versions/node/v6.10.3/bin/node" "/home/ubuntu/.nvm/versions/node/v6.10.3/bin/npm" "start" "/home/ubuntu/code/codeschool/NERM/tools/srcServer.js"
data:    tools/srcServer.js:23101 - npm ERR! node v6.10.3
data:    tools/srcServer.js:23101 - npm ERR! npm  v3.10.10
data:    tools/srcServer.js:23101 - npm ERR! code ELIFECYCLE
data:    tools/srcServer.js:23101 - npm ERR! nerm@1.0.0 start: `npm-run-all --parallel test:watch open:src lint:watch "/home/ubuntu/code/codeschool/NERM/tools/srcServer.js"`
data:    tools/srcServer.js:23101 - npm ERR! Exit status 1
data:    tools/srcServer.js:23101 - npm ERR! 
data:    tools/srcServer.js:23101 - npm ERR! Failed at the nerm@1.0.0 start script 'npm-run-all --parallel test:watch open:src lint:watch "/home/ubuntu/code/codeschool/NERM/tools/srcServer.js"'.
data:    tools/srcServer.js:23101 - npm ERR! Make sure you have the latest version of node.js and npm installed.
data:    tools/srcServer.js:23101 - npm ERR! If you do, this is most likely a problem with the nerm package,
data:    tools/srcServer.js:23101 - npm ERR! not with npm itself.
data:    tools/srcServer.js:23101 - npm ERR! Tell the author that this fails on your system:
data:    tools/srcServer.js:23101 - npm ERR!     npm-run-all --parallel test:watch open:src lint:watch "/home/ubuntu/code/codeschool/NERM/tools/srcServer.js"
data:    tools/srcServer.js:23101 - npm ERR! You can get information on how to open an issue for this project with:
data:    tools/srcServer.js:23101 - npm ERR!     npm bugs nerm
data:    tools/srcServer.js:23101 - npm ERR! Or if that isn't available, you can get their info via:
data:    tools/srcServer.js:23101 - npm ERR!     npm owner ls nerm
data:    tools/srcServer.js:23101 - npm ERR! There is likely additional logging output above.
data:    tools/srcServer.js:23101 - npm ERR! Please include the following file with any support request:
data:    tools/srcServer.js:23101 - npm ERR!     /home/ubuntu/code/codeschool/NERM/npm-debug.log
data:    tools/srcServer.js:23101 - error: Forever detected script exited with code: 1
data:    tools/srcServer.js:23101 - error: Script restart attempt #1
data:    tools/srcServer.js:23101 - > nerm@1.0.0 prestart /home/ubuntu/code/codeschool/NERM
data:    tools/srcServer.js:23101 - > babel-node tools/startMessage.js

**Comment by coryhouse** [comment]
I'll reply on the course discussion.
