### ISSUE TITLE
converting this  code to React 4?

### ISSUE THREAD

**Issue by alernerdev** [coryhouse/react-flux-starter-kit#18]
Sorry, not an issue, but didnt know where else to post it.  I have tried to do this course using React/Router 4 -- finally gave up, just too many differences, and I am a beginner with this stuff.  Did anyone try to upgrade the source code?  I gave up at the author form hydration section.  Preventing routing away from a dirty form doesnt work either, although I have taken it pretty far.  My source is here: https://github.com/alernerdev/psadmin if anyone is interested in continuing this.
THanks

**Comment by coryhouse** [comment]
Hi @alernerdev - To follow along with the course, be sure to use the exact versions I specified. And good news, [I've posted a PR here](https://github.com/coryhouse/react-flux-building-applications/pull/1) that shows how to upgrade the final course app to use the latest versions. As you'll see, most the changes are trivial except for the changes in React Router 4. :)
