### ISSUE TITLE
error  'Console' is not defined  no-undef

### ISSUE THREAD

**Issue by rmess** [coryhouse/react-flux-starter-kit#19]
I'm startin to following your class.
But I'm using Eslint 4.
After upgrading my Eslint config file as you did on your repo, when I run gulp I have the following error.

/home/laowai/dev/psadmin/src/main.js
  2:11  error  'console' is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)

**Comment by coryhouse** [comment]
Hello - To follow along, be sure to run the exact versions I specified. When you're done with the course, I show how to move to the latest versions here:  https://github.com/coryhouse/react-flux-building-applications/pull/1
