### ISSUE TITLE
Lint Issue

### ISSUE THREAD

**Issue by lipalath-ms** [coryhouse/react-flux-starter-kit#21]
After adding lint task, I get the following issue:

Error: Cannot find module 'eslint-config-defaults/configurations/eslint'.

I used the same versions you suggested in the video.

Please let me know what the issue is.

**Comment by coryhouse** [comment]
Are you using the same versions I used in the final course exercise? If that doesn’t help, please post your solution on GiHub and I’ll give it a look.
