### ISSUE TITLE
Outdated eslint config

### ISSUE THREAD

**Issue by ranst91** [coryhouse/react-flux-starter-kit#5]
I'd suggest updating the config file. The course itself is a bit outdated but that's a too big project to handle.
Yet, here are some of the things that can be updated instantly to make the pluralsight course go smoother:
update an .eslintrc.json file
update package.json with react-dom dependency that is now required

**Comment by coryhouse** [comment]
I see your point, but I'm hesitant to update the code here without also updating all videos. I have to assure that the code here operates the same as the code viewed in the course, so I'm going to leave things as is to avoid the risk of confusion.

That said, thanks for the suggestion!
