### ISSUE TITLE
No ESLint configuration found

### ISSUE THREAD

**Issue by tedjames** [coryhouse/react-flux-starter-kit#8]
After adding in the lint task, the following error occurred:

> No ESLint configuration found

In order to address this issue, I had to switch line 66 in gulpfile.js from:
`.pipe(lint({config: 'eslint.config.json'}))
`
to:
`.pipe(lint({configFile: 'eslint.config.json'}))
`

**Comment by coryhouse** [comment]
Are you running the versions listed in this starter kit? The change you're referring to only applies if you're using newer versions of gulp-eslint.

Thanks for reporting!

**Comment by tedjames** [comment]
Ahh okay that would be it! I'm running the newest version of gulp-eslint. 

Is it absolutely necessary that I use the versions you specified for the entire course? I'd prefer to continue this course using the latest releases of just about everything and I don't mind spending a little time here and there to figure out subtle changes from older versions.

Thanks for the quick response by the way!

**Comment by coryhouse** [comment]
You will generally be fine to run latest, in fact I'd be interested to hear your feedback and see your repo if you do. :) 

This is what will trip you up:

React-dom
React-router has changed significantly in the latest release
ESLint's rule structure been tweaked

**Comment by tedjames** [comment]
Awesome, thanks for the heads up! 

I'll take note of all the changes I encounter and send you over my repo once I get through your course :)

**Comment by coryhouse** [comment]
Excellent! Thanks Ted!

**Comment by anilGoy** [comment]
for me In order to address this issue, I had to switch line in gulpfile.js from:
.pipe(lint({config: 'eslint.config.js'}))
to:
.pipe(lint({configFile: 'eslint.config.json'}))
I am using  "gulp-eslint": "^4.0.0"
and worked from me :) 
Thanks for hint here

**Comment by coryhouse** [comment]
For those interested in trying the latest versions, I suggest using the versions I specify in the course / this repo to follow along, then after you finish the course, check out this PR for details on how to upgrade to the latest: https://github.com/coryhouse/react-flux-building-applications/pull/1

**Comment by coryhouse** [comment]
The course has been updated as of 6/2019 and no longer uses Gulp so this is no longer relevant.
